version: "3.3"
services:
  library:
    build:
      context: ../
      dockerfile: services/library/Dockerfile
    ports:
    - "8001:8001"
    volumes:
    - /home/fruitbat/Music:/home/fruitbat/Music


      
